91 merge stable version to main
celte-team/celte-system pull request #92
Opened 2024-12-08 16:14 UTC by ClementToni

This pull request includes all the new features add during the last sprin: 
- pulsar
- redis
- system
- master

# to test :
please take attention when testing the code, I probably forgot something.
Individual points to test: 
- pulsar:
    - ./automation/run --pulsar
- master:
    - ./automation/run --master
- redis:
    - ./automation/run --redis

- global test :
    - ./automations/run --test ./automations/test_suites/basicGameTest.yaml 

⚠️ I really encourage you tu download the [redis extension of VSCODE](https://marketplace.visualstudio.com/items?itemName=Redis.redis-for-vscode) to understand how redis and master work.
 

### Code Cleanup:
* remove kafka related file/folder
* Removed unused state handling and RPC registration code from the client source files (`CelteClient.cpp`, `StateConnected.cpp`, `StateConnecting.cpp`). [[1]](diffhunk://#diff-b47a7fd8c5aec60095721a68a85a0190f850b6defa29e5514807483908ffaa7bL1-L23) [[2]](diffhunk://#diff-96c5101cd88c5061c6ed96dd99634d3cb9cb9cfba78e1b981926b22432eb3ec4L1-L46) [[3]](diffhunk://#diff-8eb23ea6ea02920d832ae3f5b196e732f0969b16986be82fcfb95ed7b8480e86L1-L75)

2024-12-09 02:03 UTC, EliotJanvier requested changes
ok overall but some minor changes (mostly configurability)

2024-12-09 02:03 UTC, EliotJanvier commented on redis/docker-compose.yml
open for discussion but could we create a docker compose that has both pulsar & redis to up them at the same time? (maybe through a third docker compose that references the other two)

2024-12-09 02:03 UTC, EliotJanvier commented on system/runtime/include/Logger.hpp
we should open an issue to plan to incorporate redis to this logger

2024-12-09 02:03 UTC, EliotJanvier commented on system/runtime/include/nlohmann/detail/exceptions.hpp
i want a cool header like this too!

2024-12-09 17:51 UTC, ClementToni commented on master/src/Program.cs
> +        Redis.RedisClient redisClient = Redis.RedisClient.GetInstance("localhost:6379");
yes, right

2024-12-09 18:12 UTC, ClementToni commented on redis/docker-compose.yml
why not create a **--stack** (or other name) with: redis/pulsar inside a docker file ?

2024-12-09 18:13 UTC, ClementToni commented on system/runtime/include/Logger.hpp
Who should be responsible for it ? 

@EliotJanvier
@Tumulus0 
@EwenBriand

2024-12-09 18:14 UTC, ClementToni commented on system/runtime/include/Logger.hpp
Do not hesitate to ask me for an explanation of the redis stack

2024-12-09 18:17 UTC, ClementToni commented
<img width="1512" alt="Screenshot 2024-12-09 at 6 14 48 PM" src="https://github.com/user-attachments/assets/532e6000-102d-4b34-8da9-ca180aa0e8fa">
Still have a segfault since last update: 

##step to recreate the bug: 
- ./run --pulsar 
- ./run --redis
- ./run --master
- ./tests/server.debug
- ./tests/client.debug

Client connect, start to receive data, then server crash :/

2024-12-11 04:40 UTC, EliotJanvier approved these changes

2024-12-11 04:40 UTC, EliotJanvier commented on master/configFile.yml
> +kafka_brokers: 192.168.0.19:80
ip is still static, use env instead?

2024-12-12 09:12 UTC, ClementToni commented on master/configFile.yml
> +kafka_brokers: 192.168.0.19:80
Config file is supposed to be change by the developer, there is no need for an environment variable here.

2024-12-16 01:35 UTC, EliotJanvier commented on system/runtime/include/Logger.hpp
@EwenBriand  then

2024-12-16 01:41 UTC, merged